### ISSUE TITLE
DLC folder structure not dumping, files are dumped to root DLC folder

### ISSUE THREAD

**Issue by RoboFox83** [hippie68/ftpdump#5]
I noticed an issue on 7.55 and now 9.00 while using GoldenHen 2.0 FTP, where when I dump DLC if that DLC has folders inside it they are ignored and not created. All files are just dumped to the root DLC folder that gets created.

FTP
![image](https://user-images.githubusercontent.com/96218789/146303551-d48c2c12-5775-4ece-8b9e-481af9766f4d.png)

Dump
![image](https://user-images.githubusercontent.com/96218789/146303624-1abf2723-5a86-4493-9091-f20fee9f0267.png)

This next part isn't really a bug, but any plans to extract the ac.pkg data like you do for patch.pkg?
For my DLC it seems to follow this format, but not sure if that's the standard. Be great to get the param.sfo and icon data.
![image](https://user-images.githubusercontent.com/96218789/146304599-f9cb8967-3d3b-45c8-8b17-c9c47c025a35.png)

**Comment by hippie68** [comment]
Did you try the current script version? A similar bug *seems* to have been fixed recently for patch data: https://github.com/hippie68/ftpdump/issues/4
That's when I included a new debug message that will be printed if you run the script with option --debug. It shows the number of directories that are cut. That number should match the printed directory tree.

> For my DLC it seems to follow this format, but not sure if that's the standard.

I'm not sure about that, too, but will look into it.

**Comment by RoboFox83** [comment]
> Did you try the current script version? A similar bug _seems_ to have been fixed recently for patch data: #4 That's when I included a new debug message that will be printed if you run the script with option --debug. It shows the number of directories that are cut. That number should match the printed directory tree.
> 

I did see the issue with patch and I'm using the new version. I'm not seeing any of the directory being cut information when running it with debug. It shows the 4 folders then starts dumping the first one. 

![image](https://user-images.githubusercontent.com/96218789/146390507-8ccd1a09-481a-45c4-bc4d-5a1f3879f463.png)

Looking at the scripting it looks like that cut directory part should happen before the file dumping.

**Comment by RoboFox83** [comment]
> Did you try the current script version? A similar bug _seems_ to have been fixed recently for patch data: #4
> That's when I included a new debug message that will be printed if you run the script with option --debug. It shows the number of directories that are cut. That number should match the printed directory tree.

I thought I was using the new version, but I was not (Oops), unfortunately it is still not working. Here's with the debug option on it is showing it cut 4 directories, before it starts dumping the files.
![image](https://user-images.githubusercontent.com/96218789/146394306-c579f7d8-ec21-4e94-8a3a-b54be443a84d.png)

**Comment by RoboFox83** [comment]
> Did you try the current script version? A similar bug _seems_ to have been fixed recently for patch data: #4
> That's when I included a new debug message that will be printed if you run the script with option --debug. It shows the number of directories that are cut. That number should match the printed directory tree.

I'm so sorry for wasting your time here, I did see the update which prompted me to test DLC part because dump trying to use it failed. Well I actually didn't update the script.

It is working correctly with this change and the DLC is dumping properly.  Well maybe at least this might have given you an idea with the ac.pkg files, haha. Thank you!
